### ISSUE TITLE
puma fails to start with default configuration

### ISSUE THREAD

**Issue by noraj1337** [mcpa-stlouis/hack-the-arch#20]
puma fails to start with default configuration:

```
$ ./start_local
(in /home/noraj/hack-the-arch-2.0.1)
/home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/dsl.rb:26:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/dsl.rb:26:in `_load_from'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/dsl.rb:9:in `load'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:204:in `block in load'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:201:in `each'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/configuration.rb:201:in `load'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/launcher.rb:62:in `initialize'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cli.rb:65:in `new'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/lib/puma/cli.rb:65:in `initialize'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/bin/puma:8:in `new'
	from /home/noraj/.rvm/gems/ruby-2.3.1/gems/puma-3.4.0/bin/puma:8:in `<top (required)>'
	from /home/noraj/.rvm/gems/ruby-2.3.1/bin/puma:22:in `load'
	from /home/noraj/.rvm/gems/ruby-2.3.1/bin/puma:22:in `<main>'
	from /home/noraj/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/noraj/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by paullj1** [comment]
This was an oversight and will be removed in future versions.  The recommended "offline" deployment is now via a Docker Compose service.  See [Docker Readme](https://github.com/mcpa-stlouis/hack-the-arch/blob/master/DOCKER_README.md)
